Add functions for query-target GW distance calculations
CamaraLab/CAJAL pull request #17
Opened 2024-09-11 12:33 UTC by schlegelp

Hi! This PR would add functions to run query->target distance calculations, complementing the current all-by-all functionality. 

The use-case for these (at least in my work) would be to find, for each query neuron, the best match(es) among a pool of target neurons. 

TODOs:
- query->target version of:
  - [x]  GW distance
  - [ ] QGW distance 
  - [ ] SLB distance
- [ ] update docs

Before I continue working on the TODOs above, I was wondering if you think these would be a good fit? And if you do, whether you agree with the way it is implemented in this first pass?

2024-09-27 22:09 UTC, patrick-nicodemus requested changes

2024-09-27 22:09 UTC, patrick-nicodemus commented on src/cajal/run_gw.py
> +    DistanceMatrix,  # GW distance matrix (Squareform)
should be
```
Matrix,  # GW distance matrix (not necessarily a square)
```

2024-09-27 22:09 UTC, patrick-nicodemus commented on src/cajal/run_gw.py
> +        where gw_dmat is a square matrix whose (i,j) entry is the GW distance
gw_dmat is not necessarily square

2024-09-27 22:09 UTC, patrick-nicodemus commented on src/cajal/run_gw.py
> +            gw_data = csv_output_writer(
It's nice that you were able to make use of this existing function. When I wrote it I had square matrices in mind but I think this should be correct.

2024-09-27 22:09 UTC, patrick-nicodemus commented on src/cajal/run_gw.py
> +    DistanceMatrix,  # Pairwise GW distance matrix (Squareform)
```
Matrix, # Pairwise GW distance matrix (need not be square)
```

2024-09-27 22:20 UTC, patrick-nicodemus commented
Hi Philipp,
Thanks very much for this contribution. It looks great.
I think the code is simple and clear.
I think the overall architecture / structure is good and fits in with other parts of the library.
Thank you very much for writing type annotations and adding a unit test.

I don't have any comments on the code but there are a few changes to the docstrings and type labels I suggested.

The way the code currently stands, the type `DistanceMatrix` refers to a square, symmetric distance matrix with zeroes along the diagonal. I have been using the name `Matrix = NewType("Matrix", npt.NDArray[np.float64])` to refer to a numpy array of shape 2.

 We can rename the type to something else to make it easier to distinguish between square symmetric distance matrices and general rectangular distance matrices, but on the other hand the distance matrices in the query/target code don't have any special properties other than being nonnegative, so perhaps they need a special name.

For future work, I don't think it's necessary (for computational reasons, at least) to do something like this for the SLB distances, which I expect to be sufficiently fast to compute that one can just do all-by-all comparisons and then filter afterwards. Although the SLB is itself a poor estimator of GW, in its own right it seems to give reasonably good performance on our k-nn classifier tests, so it may be of direct use.

On the other hand, I do think that implementing the query version of the QGW is likely to be useful, and the design can be basically identical to the design of this one. It would be nice to unify some of this redundant code but I am not sure that the benefits of a uniform interface would outweigh the increased complexity (in Python, at least).

Again, thank you for this contribution!

2026-01-20 18:49 UTC, lincolnwu approved these changes
Approved

2026-01-20 18:50 UTC, lincolnwu approved these changes
Approved

2026-01-20 19:00 UTC, merged